SiliconApp/Controllers/ContactController.cs
using Microsoft.AspNetCore.Mvc;

namespace SiliconApp.Controllers;

public class ContactController : Controller
{
    public IActionResult Index()
    {
        ViewData["Title"] = "Contact Us!";
        return View();
    }
}

SiliconApp/Controllers/CoursesController.cs
using Microsoft.AspNetCore.Mvc;
using Newtonsoft.Json;
using WebApi.Entities;

namespace SiliconApp.Controllers;

public class CoursesController : Controller
{
    [Route("/courses")]
    [HttpGet]
    public async Task<IActionResult> Courses()
    {
        //hämtar in information till vår vy med hjälp av httpclient som går till url:en på wep apiet.
        using var http = new HttpClient();
        var response = await http.GetAsync("https://localhost:7296/api/courses");
        var json = await response.Content.ReadAsStringAsync();
        var data = JsonConvert.DeserializeObject<IEnumerable<CourseEntity>>(json);

        return View(data);
    }

    [Route("/courses/details")]
    [HttpGet]
    public IActionResult CourseDetail()
    {
        return View();
    }

    [Route("/courses/saved")]
    [HttpGet]
    public IActionResult SavedCourses()
    {
        return View();
    }
}

SiliconApp/Views/Shared/Sections/_AccessDeniedPartial.cshtml
@{
    ViewData["Title"] = "Access denied!";
}

<section class="notfound">
    <div class="container">
        <div class="content">
            <span class="d5">Ooops! Access denied</span>
            <p>Looks like you don´t have the rights to access this page</p>
            <a class="btn-theme" asp-controller="Home" asp-action="Index"><i class="fa-regular fa-house"></i>Go to homepage</a>
        </div>
    </div>
</section>

SiliconApp/Views/Shared/Sections/_AdminPortalPartial.cshtml
@{
    ViewData["Title"] = "Admin Portal";
}

<section>
    <div class="container">
        <h1>@ViewData["Title"]</h1>
    </div>
</section>

SiliconApp/Views/Shared/Sections/_ContactPartial.cshtml
<section class="contact">
    <div class="container">
        <div class="info-text">
            <i class="fa-regular fa-house"></i>
            <p>Home</p>
            <i class="fa-sharp fa-solid fa-forward"></i>
            <a href="#">Contact</a>
        </div>
        <h1>Contact Us</h1>
        <div class="aside">
            <div class="content">
                <img src="~/images/icons/icon-mail.svg" alt="">
                <div class="content-group">
                    <h4>Email us</h4>
                    <p>Please feel free to drop us a line. We will respond as soon as possible.</p>
                    <a href="#">Leave a message<i class="fa-regular fa-arrow-right"></i></a>
                </div>
            </div>
            <div class="content">
                <img src="~/images/icons/icon-add.svg" alt="">
                <div class="content-group">
                    <h4>Careers</h4>
                    <p>Sit ac ipsum leo lorem magna nunc mattis maecenas non vestibulum.</p>
                    <a href="#">Send an application<i class="fa-regular fa-arrow-right"></i></a>
                </div>
            </div>
        </div>
        <div class="contact-form">
            <form method="post">
                <h2>Get In Contact With Us</h2>
                <div class="content">
                    <div id="form-fullname" class="input-group">
                        <label for="fullname">Full name</label>
                        <input type="text">
                    </div>
                    <div id="form-email" class="input-group">
                        <label for="email">Email address</label>
                        <input type="text">
                    </div>
                    <div id="form-service" class="input-group">
                        <label for="service">Service <span>(Optional)</span></label>
                        <select id="select-service" name="select" title="select-service">
                            <option class="option" value="option"></option>
                            <option class="option" value="option"></option>
                            <option class="option" value="option"></option>
                        </select>
                    </div>
                    <div id="form-message" class="input-group">
                        <label for="message">Message</label>
                        <textarea class="message" name="message" rows="7" cols="50">Enter your message here..</textarea>
                    </div>
                    <button id="form-button" class="btn-theme" type="submit">Send Contact Request</button>
                </div>
            </form>
        </div>
    </div>
    <img class="map" src="~/images/image/map.svg" alt="map">
</section>

SiliconApp/Views/Shared/Sections/_CoursesPartial.cshtml
@using WebApi.Entities

@model IEnumerable<CourseEntity>

<section class="courses">
    <div class="container">
        <div class="content-box">
            @foreach(var course in Model)
            {
                <a class="display-course" href="#">
                    <img class="course-img" src="~/images/image/@course.ImageUrl" alt="picture of hands writing on a desktop-board">
                    <div class="badge">
                        @if (course.IsBestSeller == true)
                        {
                            <p>Best Seller</p>
                        }
                        <img class="icon" src="~/images/icons/s-btn.svg">
                    </div>
                    <div class="display-info">
                        <h5>@course.Title</h5>
                        <p>@course.Author</p>
                        <span>@course.Price</span>
                        <hr>
                        <div class="timeline-info">
                            <i class="fa-light fa-clock"></i>
                            <p>@course.Hours</p>
                            <i class="fa-light fa-thumbs-up"></i>
                            <p>@course.LikesInProcent (@course.LikesInNumbers)</p>
                        </div>
                    </div>
                </a>
            }
           
@*             <a class="display-course" href="#">
                <img class="course-img" src="~/images/image/html_course.svg" alt="picture of laptop">
                <div class="badge">
                    <img src="~/images/icons/s-btn.svg">
                </div>
                <div class="display-info">
                    <h5>HTML, CSS, JavaScript Web Developer</h5>
                    <p>By Jenny Wilson & Marvin McKinney</p>
                    <span>$15.99</span>
                    <hr>
                    <div class="timeline-info">
                        <i class="fa-light fa-clock"></i>
                        <p>160 hours</p>
                        <i class="fa-light fa-thumbs-up"></i>
                        <p>92% (3.1K)</p>
                    </div>
                </div>
            </a>

            <a class="display-course" href="#">
                <img class="course-img" src="~/images/image/frontend_course.svg" alt="picture of a woman with headphones watching a laptop">
                <div class="badge">
                    <img src="~/images/icons/s-btn.svg">
                </div>
                <div class="display-info">
                    <h5>The Complete Front-End Web Development Course</h5>
                    <p>By Albert Flores</p>
                    <span>$44.99</span>
                    <hr>
                    <div class="timeline-info">
                        <i class="fa-light fa-clock"></i>
                        <p>100 hours</p>
                        <i class="fa-light fa-thumbs-up"></i>
                        <p>98% (2.7K)</p>
                    </div>
                </div>
            </a>

            <a class="display-course" href="#">
                <img class="course-img" src="~/images/image/ios_course.svg" alt="picture of a woman in glasses">
                <div class="badge">
                    <img src="~/images/icons/s-btn.svg">
                </div>
                <div class="display-info">
                    <h5>iOS & Swift - The Complete iOS App Development Course</h5>
                    <p>By Marvin McKinney</p>
                    <span>$15.99</span>
                    <hr>
                    <div class="timeline-info">
                        <i class="fa-light fa-clock"></i>
                        <p>160 hours</p>
                        <i class="fa-light fa-thumbs-up"></i>
                        <p>92% (3.1K)</p>
                    </div>
                </div>
            </a>

            <a class="display-course" href="#">
                <img class="course-img" src="~/images/image/datascience_course.svg" alt="picture of a woman in a chair">
                <div class="badge">
                    <p>Best Seller</p>
                    <img src="~/images/icons/s-btn.svg">
                </div>
                <div class="display-info">
                    <h5>Data Science & Machine Learning with Python</h5>
                    <p>By Esther Howard</p>
                    <span>$11.20</span>
                    <hr>
                    <div class="timeline-info">
                        <i class="fa-light fa-clock"></i>
                        <p>160 hours</p>
                        <i class="fa-light fa-thumbs-up"></i>
                        <p>92% (3.1K)</p>
                    </div>
                </div>
            </a>

            <a class="display-course" href="#">
                <img class="course-img" src="~/images/image/cssdrawing_course.svg" alt="picture of a woman reading from a notebook">
                <div class="badge">
                    <img src="~/images/icons/s-btn.svg">
                </div>
                <div class="display-info">
                    <h5>Creative CSS Drawing Course: Make Art With CSS</h5>
                    <p>By Robert Fox</p>
                    <span>$10.50</span>
                    <hr>
                    <div class="timeline-info">
                        <i class="fa-light fa-clock"></i>
                        <p>220 hours</p>
                        <i class="fa-light fa-thumbs-up"></i>
                        <p>94% (4.2K)</p>
                    </div>
                </div>
            </a>

            <a class="display-course" href="#">
                <img class="course-img" src="~/images/image/vgame_course.svg" alt="picture of a woman with headphones">
                <div class="badge">
                    <img src="~/images/icons/s-btn.svg">
                </div>
                <div class="display-info">
                    <h5>Blender Character Creator v2.0 for Video Games Design</h5>
                    <p>By Ralph Edwards</p>
                    <span>$18.99</span>
                    <hr>
                    <div class="timeline-info">
                        <i class="fa-light fa-clock"></i>
                        <p>160 hours</p>
                        <i class="fa-light fa-thumbs-up"></i>
                        <p>92% (3.1K)</p>
                    </div>
                </div>
            </a>

            <a class="display-course" href="#">
                <img class="course-img" src="~/images/image/mgame_course.svg" alt="picture of a man with headphones">
                <div class="badge">
                    <img src="~/images/icons/s-btn.svg">
                </div>
                <div class="display-info">
                    <h5>The Ultimate Guide to 2D Mobile Game Development with Unity</h5>
                    <p>By Albert Flores</p>
                    <span>$44.99</span>
                    <hr>
                    <div class="timeline-info">
                        <i class="fa-light fa-clock"></i>
                        <p>100 hours</p>
                        <i class="fa-light fa-thumbs-up"></i>
                        <p>98% (2.7K)</p>
                    </div>
                </div>
            </a>

            <a class="display-course" href="#">
                <img class="course-img" src="~/images/image/test_course.svg" alt="picture of a man in glasses">
                <div class="badge">
                    <img src="~/images/icons/s-btn.svg" alt="">
                </div>
                <div class="display-info">
                    <h5>Learn JMETER from Scratch on Live Apps-Performance Testing</h5>
                    <p>By Jenny Wilson</p>
                    <span>$14.50</span>
                    <hr>
                    <div class="timeline-info">
                        <i class="fa-light fa-clock"></i>
                        <p>160 hours</p>
                        <i class="fa-light fa-thumbs-up"></i>
                        <p>92% (3.1K)</p>
                    </div>
                </div>
            </a> *@
        </div>
        <nav aria-label="Pages">
            <ul class="pagination">
                <li class="page-item">
                    <a class="page-link" href="#" aria-label="Previous">
                        <span aria-hidden="true">&laquo;</span>
                    </a>
                </li>
                <li class="page-item"><a class="page-link" href="#">1</a></li>
                <li class="page-item"><a class="page-link" href="#">2</a></li>
                <li class="page-item"><a class="page-link" href="#">3</a></li>
                <li class="page-item">
                    <a class="page-link" href="#" aria-label="Next">
                        <span aria-hidden="true">&raquo;</span>
                    </a>
                </li>
            </ul>
        </nav>
    </div>
</section>

SiliconApp/Views/Shared/Sections/_CoursesShowcasePartial.cshtml
<section class="courses-showcase">
    <div class="container">
        <div class="info-text">
            <i class="fa-regular fa-house"></i>
            <p>Home</p>
            <i class="fa-sharp fa-solid fa-forward"></i>
            <a href="#">Courses</a>
        </div>
        <div class="menu">
            <div class="content">
                <h1>Courses</h1>
                <div class="input-menu">
                    <div class="dropdown">
                        <div class="styled">
                            <select id="select-course" name="select" title="select-course">
                                <option class="categories" value="categories">All categories</option>
                                <option value="fullstack">Fullstack Web Developer</option>
                                <option value="html-css-js">HTML, CSS, JavaScript</option>
                                <option value="frontend">Front-End Web Development</option>
                                <option value="iosapp">iOS App Development</option>
                                <option value="datascience">Data Science & Machine Learning</option>
                                <option value="css-drawing">CSS Drawing Course</option>
                                <option value="video-game">Video Games Design</option>
                                <option value="mobile-game"> Mobile Game Development</option>
                                <option value="Testing">Testing</option>
                            </select>
                            <div class="search-box active">
                                <span>
                                    <i class="fa-regular fa-magnifying-glass"></i>
                                </span>
                                <input class="search" type="text" placeholder="Search courses">
                            </div>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>
</section>

SiliconApp/Views/Shared/Sections/_DetailsPartial.cshtml
@{
    var user = await UserManager.GetUserAsync(User);
}

@model AccountDetailsViewModel
@{
    ViewData["Title"] = $"{Model.ProfileInfo!.FirstName} {Model.ProfileInfo.LastName}";
}

<section class="account-details">
    <div class="container">
        <div class="aside">
            <div class="profile">
                @if (user != null)
                {
                    <img src="~/uploads/@user.ProfileImageUrl" alt="profile image">

                    <form enctype="multipart/form-data" method="post" asp-action="UploadImage" asp-controller="Account">
                        <input id="fileUploader" type="file" name="file" hidden />
                        <label for="fileUploader" class="btn-transparent"><i class="fa-regular fa-refresh"></i></label>
                    </form>
                }
                <h5>@Model.ProfileInfo.FirstName @Model.ProfileInfo.LastName</h5>
                <p>@Model.ProfileInfo.Email</p>
                <div class="sidebar">
                    <a class="btn-theme" asp-controller="Account" asp-action="Details"><i class="fa-regular fa-gear"></i><span>Account Details</span></a>
                    <a class="btn-transparent" asp-controller="Authentication" asp-action="Security"><i class="fa-regular fa-lock"></i><span>Security</span></a>
                    <a class="btn-transparent" asp-controller="Courses" asp-action="SavedCourses"><i class="fa-regular fa-bookmark"></i><span>Saved Courses</span></a>
                    <a class="btn-transparent" asp-controller="Authentication" asp-action="SignOut"><i class="fa-regular fa-arrow-right-from-bracket"></i><span>Sign Out</span></a>
                </div>
            </div>
        </div>
        <div class="account-forms">
            <form method="post" asp-controller="Account" asp-action="Details" novalidate>
                <h2>Account Details</h2>
                <h5>Basic Info</h5>

                <div class="account-profileinfo">
                    <div id="form-firstname" class="input-group">
                        <label asp-for="BasicInfo!.FirstName"></label>

                        @if (Model.ProfileInfo.IsExternalAccount)
                        {
                            <input asp-for="BasicInfo!.FirstName" disabled>
                        }
                        else
                        {
                            <input asp-for="BasicInfo!.FirstName">
                            <span asp-validation-for="BasicInfo!.FirstName"></span>
                        }
                    </div>
                    <div id="form-lastname" class="input-group">
                        <label asp-for="BasicInfo!.LastName"></label>

                        @if (Model.ProfileInfo.IsExternalAccount)
                        {
                            <input asp-for="BasicInfo!.LastName" disabled>
                        }
                        else
                        {
                            <span asp-validation-for="BasicInfo!.LastName"></span>
                            <input asp-for="BasicInfo!.LastName">
                        }
                    </div>
                    <div id="form-email" class="input-group">
                        <label asp-for="BasicInfo!.Email"></label>

                        @if (Model.ProfileInfo.IsExternalAccount)
                        {
                            <input asp-for="BasicInfo!.Email" disabled>
                        }
                        else
                        {
                            <span asp-validation-for="BasicInfo!.Email"></span>
                            <input asp-for="BasicInfo!.Email">
                        }
                    </div>
                    <div id="form-phone" class="input-group">
                        <label asp-for="BasicInfo!.Phone"></label>
                        <span asp-validation-for="BasicInfo!.Phone"></span>
                        <input asp-for="BasicInfo!.Phone">
                    </div>
                    <div id="form-bio" class="input-group">
                        <label asp-for="BasicInfo!.Biography">Bio <span>(optional)</span></label>
                        <textarea class="bio" asp-for="BasicInfo!.Biography" rows="4" cols="50"></textarea>
                    </div>
                    <div class="menu-buttons">
                        <button id="form-btn-gray" class="btn-gray"><span>Cancel</span></button>
                        <button id="form-btn-theme" class="btn-theme" type="submit"><span>Save changes</span></button>
                    </div>
                </div>
            </form>
            <form method="post" asp-controller="Account" asp-action="Details" novalidate>
                <hr>
                <h5>Address</h5>
                <div class="account-address">
                    <div id="form-addressline-1" class="input-group">
                        <label asp-for="AddressInfo!.StreetName">Address line 1</label>
                        <span asp-validation-for="AddressInfo!.StreetName"></span>
                        <input asp-for="AddressInfo!.StreetName">
                    </div>
                    <div id="form-addressline-2" class="input-group">
                        <label asp-for="AddressInfo!.SecondStreetName">Address line 2</label>
                        <span asp-validation-for="AddressInfo!.SecondStreetName"></span>
                        <input asp-for="AddressInfo!.SecondStreetName">
                    </div>
                    <div id="form-postalcode" class="input-group">
                        <label asp-for="AddressInfo!.PostalCode">Postalcode</label>
                        <span asp-validation-for="AddressInfo!.PostalCode"></span>
                        <input asp-for="AddressInfo!.PostalCode">
                    </div>
                    <div id="form-city" class="input-group">
                        <label asp-for="AddressInfo!.City">City</label>
                        <span asp-validation-for="AddressInfo!.City"></span>
                        <input asp-for="AddressInfo!.City">
                    </div>
                    <div class="menu-buttons">
                        <button id="form-btn-gray" class="btn-gray"><span>Cancel</span></button>
                        <button id="form-btn-theme" class="btn-theme" type="submit"><span>Save changes</span></button>
                    </div>
                </div>
            </form>
        </div>
    </div>
</section>

SiliconApp/Views/Shared/Sections/_FooterPartial.cshtml
<footer>
    <div class="container">
        @* när man går till sidan authentication ska inte socialmedia knapparna synas *@
        <div class="@((ViewContext.RouteData.Values["Controller"]!.ToString() == "Authentication") ? " d-none" : "socialmedia")">
            <a class="btn-socialmedia" href="#"><i class="fa-brands fa-square-facebook"></i></a>
            <a class="btn-socialmedia" href="#"><i class="fa-brands fa-twitter"></i></a>
            <a class="btn-socialmedia" href="#"><i class="fa-brands fa-square-instagram"></i></a>
            <a class="btn-socialmedia" href="#"><i class="fa-brands fa-youtube"></i></a>
        </div>
        <div class="copyrights">
            &copy; @DateTime.Now.Year Silicon All rights reserved
            <p>.Pulvinar urna condimentum amet tempor, ornare integer. Lorem odio justo malesuada suspendisse viverra aliquet quisque turpis non. Feugiat in odio non nunc ornare consectetur.</p>
        </div>
    </div>
</footer>

SiliconApp/Views/Shared/Sections/_GetStartedPartial.cshtml
<section class="getstarted">
    <div class="container">
        <div class="content">
            <p>Ready to get started?</p>
            <h1>Take Your<span> Skills</span> to the Next Level</h1>
            <div>
                <button class="btn-theme">Work with us</button>
            </div>
        </div>
        <div>
            <img src="~/images/image/group.svg" alt="drawing of a desktop, woman & laptop">
        </div>
    </div>
</section>

SiliconApp/Views/Shared/Sections/_HeaderPartial.cshtml
@{
    var themeMode = Context.Request.Cookies["ThemeMode"] ?? "light";
    var isDark = (themeMode == "dark") ? true : false;
}
@inject SignInManager<UserEntity> _signInManager

<header>
    <div class="container">
        <a id="logo" asp-controller="Home" asp-action="Index">
            <img src="~/images/@(isDark ? "silicondarklogo.svg" : "siliconlogo.svg")" alt="silicon logotype">
            </a>
        <div class="menu">
            <nav>
              @*   fragment används när vi vill kunna gå till olika sektioner på sidan *@
                <a class="menu-link" asp-controller="Home" asp-action="Index" asp-fragment="overview">Overview</a>

               @if (_signInManager.IsSignedIn(User))
                {
                    <a class="menu-link" asp-controller="Courses" asp-action="Courses">Courses</a>
                }
                else
                {
                    <a class="menu-link" asp-controller="Home" asp-action="Index" asp-fragment="features">Features</a>
                }
                @if (User.IsInRole("Admin")) // bara den som har rollen admin(eller annan som du lägger till) kan se länken till sidan
                {
                    <a class="menu-link" asp-controller="Admin" asp-action="Index">Admin Portal</a>
                }

                <a class="menu-link" asp-controller="Contact" asp-action="Index">Contact</a>
            </nav>
        </div>
        <div class="btn-switch">
            <label>Light</label>
            <label class="switch" for="switch-mode">
                <input type="checkbox" id="switch-mode" checked="@isDark" />
                <span class="slider round"></span>
            </label>
            <label>Dark</label>
        </div>
        <div class="menu-buttons">
           
            @if(_signInManager.IsSignedIn(User))
            {
                <a class="btn-gray" asp-controller="Authentication" asp-action="SignOut"><i class="fa-sharp fa-regular fa-arrow-right-from-bracket"></i><span>Sign out</span></a>
                <a asp-controller="Account" asp-action="Details"><img src="~/images/profilelogotype.svg" alt="profile image"></a>
            }
            else
            {
                <a class="btn-gray" asp-controller="Authentication" asp-action="SignIn"><i class="fa-sharp fa-regular fa-arrow-right-to-bracket"></i><span>Sign in</span></a>
                <a class="btn-theme" asp-controller="Authentication" asp-action="SignUp"><i class="fa-regular fa-user"></i><span>Sign up</span></a>
            }
        </div>
        <button class="mobile-btn" onclick="openNav()">
            <span>
                <i class="fa-regular fa-bars"></i>
            </span>
        </button>

        <div id="myNav" class="overlay">
            <button class="closebtn" onclick="closeNav()">&times;</button>
            <div class="overlay-content">
                <a href="#">Overwiew</a>
                <a href="#">Features</a>
                <a href="#">Contacts</a>
                <div class="menu-buttons">
                    @if (_signInManager.IsSignedIn(User))
                    {
                        <a class="btn-gray" asp-controller="Authentication" asp-action="SignOut"><i class="fa-sharp fa-regular fa-arrow-right-from-bracket"></i><span>Sign out</span></a>
                        <a class="img" asp-controller="Account" asp-action="Details"><img src="~/images/profilelogotype.svg" alt="profile image"></a>
                    }
                    else
                    {
                        <a class="btn-gray" asp-controller="Authentication" asp-action="SignIn"><i class="fa-sharp fa-regular fa-arrow-right-to-bracket"></i><span>Sign in</span></a>
                        <a class="btn-theme" asp-controller="Authentication" asp-action="SignUp"><i class="fa-regular fa-user"></i><span>Sign up</span></a>
                    }
                </div>
                <div class="socialmedia">
                    <a class="btn-socialmedia" href="#"><i class="fa-brands fa-square-facebook"></i></a>
                    <a class="btn-socialmedia" href="#"><i class="fa-brands fa-twitter"></i></a>
                    <a class="btn-socialmedia" href="#"><i class="fa-brands fa-square-instagram"></i></a>
                    <a class="btn-socialmedia" href="#"><i class="fa-brands fa-youtube"></i></a>
                </div>
                <div class="copyrights">
                    &copy; 2024 Silicon. All rights reserved
                    <p>Pulvinar urna condimentum amet tempor, ornare integer</p>
                </div>
            </div>
        </div>
    </div>
</header>

SiliconApp/Views/Shared/Sections/_SecurityPartial.cshtml
<section class="account-details">
    <div class="container">
        <div class="aside">
            <div class="profile">
                <img src="~/images/image/profileimage.svg" alt="">
                <h5>John Doe</h5>
                <p>john.doe@domain.com</p>
                <div class="sidebar">
                    <a class="btn-theme" asp-controller="Account" asp-action="Details"><i class="fa-regular fa-gear"></i><span>Account Details</span></a>
                    <a class="btn-transparent" asp-controller="Authentication" asp-action="Security"><i class="fa-regular fa-lock"></i><span>Security</span></a>
                    <a class="btn-transparent" asp-controller="Courses" asp-action="SavedCourses"><i class="fa-regular fa-bookmark"></i><span>Saved Courses</span></a>
                    <a class="btn-transparent" asp-controller="Authentication" asp-action="SignOut"><i class="fa-regular fa-arrow-right-from-bracket"></i><span>Sign Out</span></a>
                </div>
            </div>
        </div>
        <div class="account-forms">
            <form method="post">
                <h2>Security</h2>
                <h5>Password</h5>

                <div class="account-securityinfo">
                    <div id="form-password" class="input-group">
                        <label for="password">Current password</label>
                        <input type="text">
                    </div>
                    <div id="form-newPassword" class="input-group">
                        <label for="newPassword">New Password</label>
                        <input type="text">
                    </div>
                    <div id="form-confirm" class="input-group">
                        <label for="confirm">Confirm new password</label>
                        <input type="text">
                    </div>
                </div>
                <div class="menu-buttons">
                    <button id="form-btn-gray" class="btn-gray"><span>Cancel</span></button>
                    <button id="form-btn-theme" class="btn-theme"><span>Change password</span></button>
                </div>
            </form>
            <form method="post">
                <hr>
                <h5>Delete account</h5>
                <div class="account-delete">
                    <div id="read-terms">
                        <p>When you delete your account, your public profile will be deactivated immediately. If you change your mind before the 14 days are up, sign in with your email and password, and we’ll send you a link to reactivate your account.</p>
                    </div>
                    <div id="form-accept" class="checkbox-group">
                        <input type="checkbox">
                        <label for="checkbox">Yes, I want to delete my account.</label>
                    </div>
                    <div class="menu-button">
                        <button id="form-btn-delete" class="btn-delete"><span>Delete</span></button>
                    </div>
                </div>
            </form>
        </div>
    </div>
</section>
@await Html.PartialAsync("_ValidationScriptPartial")